  name: CleanArchitecture
  on:
    pull_request:
      branches: [ main ]
    push:
      branches: [ main ]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1

        - name: Setup Java JDK
          uses: actions/setup-java@v4.1.0
          with:
            distribution: 'adopt'

        - name: Build with Gradle
          run: ./gradlew build

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.3.1
          with:
            name : cleanArchitecture.apk
            path: app/build/output/debug/apk/app_debug.apk









